apiVersion: v1
kind: PersistentVolume
metadata:
  name: ruoyi-mysql-pv-volume
  labels:
    type: local
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: {{ .Values.storageClass }}
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/ruoyi/mysql"