apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ruoyi-mysql-pv-claim
  annotations:
     "helm.sh/hook-weight": "-4"

spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi