apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        admission.datakit/java-lib.version: ""
        datakit/logging.logs: |
          [
            {
              "disable": false,
              "type": "file",
              "path":"/data/logs/ruoyi-auth",
              "source":  "{{ .Values.ruoyi.prefix }}-auth"
            },
            {
              "disable": false,
              "source":  "{{ .Values.ruoyi.prefix }}-auth-output"
            }
          ]
    spec:
      containers:
        - name: auth-container
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: JAVA_OPTS
              value: |-
                -javaagent:/datadog-lib/dd-java-agent.jar -XX:FlightRecorderOptions=stackdepth=256 -Ddd.service={{ .Values.ruoyi.prefix }}-auth  -Ddd.logs.injection=true -Ddd.profiling.enabled=true -Ddd.profiling.ddprof.enabled=true -Ddd.profiling.ddprof.cpu.enabled=true -Ddd.profiling.ddprof.wall.enabled=true -Ddd.profiling.ddprof.alloc.enabled=true -Ddd.profiling.ddprof.liveheap.enabled=true -Ddd.tags=container_host:$(POD_NAME) -Ddd.service.mapping=mysql:{{ .Values.ruoyi.prefix }}-mysql,redis:{{ .Values.ruoyi.prefix }}-redis -Ddd.env={{ .Values.ruoyi.env }} -Ddd.version={{ .Values.ruoyi.version }} -Ddd.agent.port=9529
            - name: PARAMS
              value: "--spring.redis.host=redis-service --spring.nacos.ip=nacos-service"
          image: {{ .Values.global.docker_registry }}/{{ .Values.global.docker_namespace }}/demo-ruoyi-auth:{{ .Values.global.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - name: auth-log
              mountPath: /data/app/logs

      restartPolicy: Always
      volumes:
        - name: auth-log
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate