apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-auth
  
  labels:
    app: ruoyi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-auth
  template:
    metadata:
      labels:
        app: ruoyi-auth
      annotations:
        datakit/auth-container.logs: |
          [
            {
              "disable": false,
              "type": "file",
              "path":"/data/app/logs/**/*.log",
              "source": "ruoyi-auth"
            },
            {
              "disable": false,
              "source": "ruoyi-auth"
            }
          ]
    spec:
      containers:
        - name: auth-container
          resources:
          {{- toYaml .Values.global.resources | nindent 12 }}
          env:
            - name: PARAMS
              value: "--spring.redis.host=redis-service --spring.nacos.ip=nacos-service"
          image: {{ .Values.global.docker_registry }}/{{ .Values.global.docker_namespace }}/demo-ruoyi-auth:{{ .Values.global.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - name: auth-log
              mountPath: /data/app/logs

      restartPolicy: Always
      volumes:
        - name: auth-log
          emptyDir: {}
