apiVersion: v1
kind: Service
metadata:
  name: web-service
  
  labels:
    app: web-service
spec:
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 80
  type: NodePort