apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 9299
      targetPort: 9299
  type: ClusterIP