apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-system
  
  labels:
    app: ruoyi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-system
  template:
    metadata:
      labels:
        app: ruoyi-system
      annotations:
        datakit/system-container.logs: |
          [
            {
              "disable": false,
              "type": "file",
              "path":"/data/app/logs/**/*.log",
              "source": "ruoyi-system"
            },
            {
              "disable": false,
              "source": "ruoyi-system"
            }
          ]
    spec:
      containers:
        - name: system-container
          resources:
          {{- toYaml .Values.global.resources | nindent 12 }}
          env:
            - name: PARAMS
              value: "--spring.redis.host=redis-service --spring.nacos.ip=nacos-service"
          image:   {{ .Values.global.docker_registry }}/{{ .Values.global.docker_namespace }}/demo-ruoyi-system:{{ .Values.global.version }}
          imagePullPolicy: Always

          ports:
            - containerPort: 9201
              protocol: TCP
          volumeMounts:
            - name: system-log
              mountPath: /data/app/logs

      restartPolicy: Always
      volumes:
        - name: system-log
          emptyDir: {}
