apiVersion: v1
kind: Service
metadata:
  name: system-service
  
spec:
  selector:
    app: ruoyi-system
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
  type: ClusterIP
