apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    prod: nacos
  name: ruoyi-nacos
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: ruoyi-nacos
  selector:
    matchLabels:
      prod: nacos
  template:
    metadata:
      labels:
        prod: nacos
    spec:
      containers:
        - env:
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: hostname
            - name: MODE
              value: standalone
            - name: EMBEDDED_STORAGE
              value: embedded
          image: {{ .Values.global.docker_registry }}/{{ .Values.global.docker_namespace }}/demo-ruoyi-nacos:{{ .Values.global.version }}
          imagePullPolicy: Always
          name: nacos
          ports:
            - containerPort: 8848
              name: http
              protocol: TCP
            - containerPort: 9848
              name: client-rpc
              protocol: TCP
            - containerPort: 9849
              name: raft-rpc
              protocol: TCP
            - containerPort: 7848
              name: old-raft-rpc
              protocol: TCP
          volumeMounts:
            - mountPath: /home/nacos/plugins/peer-finder
              name: data
              subPath: peer-finder
            - mountPath: /home/nacos/data
              name: data
              subPath: data
            - mountPath: /home/nacos/logs
              name: data
              subPath: logs
      volumes:
        - emptyDir: {}
          name: data
