apiVersion: v1
kind: Service
metadata:
  labels:
    prod: nacos
  name: nacos-service
  
spec:
  ports:
    - name: http
      port: 8848
      protocol: TCP
      targetPort: 8848
    - name: client-rpc
      port: 9848
      protocol: TCP
      targetPort: 9848
    - name: raft-rpc
      port: 9849
      protocol: TCP
      targetPort: 9849
    - name: old-raft-rpc
      port: 7848
      protocol: TCP
      targetPort: 7848
  selector:
    prod: nacos
  type: NodePort