FROM eclipse-temurin:8u382-b05-jre
MAINTAINER Harlon

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

ENV jar ruoyi-gateway.jar
ENV workdir /data/app/
RUN mkdir -p ${workdir}
COPY ./jar/${jar} ${workdir}
COPY ../../tool/pkg/opentelemetry-javaagent.jar ${workdir}
COPY ../../tool/pkg/pyroscope-otel_v1.0.4.jar ${workdir}
WORKDIR ${workdir}
ENTRYPOINT ["sh", "-ec", "exec java ${JAVA_OPTS} -jar ${jar} ${PARAMS} 2>&1 > /dev/null"]