name: Build and push ruoyi ui demo images

on:
  push:
    branches:
      - dev-opentelemetry-benjamin
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with NPM
        run: |
          # export NODE_OPTIONS=--openssl-legacy-provider
          cd ./src/ruoyi-ui
          npm install --registry=https://registry.npmmirror.com #安装依赖
          npm run build:prod #执行前端打包

      - name: Copy dist to folder
        run: cd ./src/docker && bash copy-html.sh
        shell: bash

      - name: Log in to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push demo images
        uses: docker/build-push-action@v3.3.1
        with:
          context: ./src/docker/nginx
          file: ./src/docker/nginx/dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-ruoyi-web:${{ github.sha }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-ruoyi-web:latest
