name: Build and push ruoyi java demo images

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        file_tag:
          - file: ./src/docker/nacos/dockerfile
            repo: demo-ruoyi-nacos
            context: ./src/docker/nacos
          - file: ./src/docker/mysql/dockerfile
            repo: demo-ruoyi-mysql
            context: ./src/docker/mysql
          - file: ./src/docker/redis/dockerfile
            repo: demo-ruoyi-redis
            context: ./src/docker/redis
          - file: ./src/docker/ruoyi/gateway/dockerfile
            repo: demo-ruoyi-gateway
            context: ./src/docker/ruoyi/gateway
          - file: ./src/docker/ruoyi/auth/dockerfile
            repo: demo-ruoyi-auth
            context: ./src/docker/ruoyi/auth
          - file: ./src/docker/ruoyi/modules/system/dockerfile
            repo: demo-ruoyi-system
            context: ./src/docker/ruoyi/modules/system

    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: Linux-java-0708c922d4bf4dab90192af21a5e94f25f35379430c7d269d18c20fe0d77cc10
          restore-keys: |
            Linux-java-

      - name: Build with Maven
        run: cd src && mvn clean package -Dmaven.test.skip=true

      - name: Copy jar to folder
        run: cd ./src/docker && bash copy-jar.sh
        shell: bash

      - name: Log in to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Matrix Build and push demo images
        uses: docker/build-push-action@v3.3.1
        with:
          context: ${{ matrix.file_tag.context }}
          file: ${{ matrix.file_tag.file }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ matrix.file_tag.repo }}:${{ github.sha }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ matrix.file_tag.repo }}:latest
          cache-from: type=gha
          cache-to: type=gha
